In [3]:
import math as m

In [4]:
m.sqrt(10)

3.1622776601683795

In [5]:
import numpy as np

In [18]:
a = [1,2,"shs"]
b = np.array(a)
b

array(['1', '2', 'shs'], 
      dtype='<U21')

In [51]:
a = [1,2,'23']
b = np.array(a, dtype='int32')
c = np.zeros(10)
d = np.ones(3)
e = np.arange(1, 4, 1)
b, c.dtype, d, e

(array([ 1,  2, 23], dtype=int32),
 dtype('float64'),
 array([ 1.,  1.,  1.]),
 array([1, 2, 3]))

In [41]:
b.sum(), b.mean(), b.shape

(26, 8.6666666666666661, (3,))

In [43]:
b.size

3

In [50]:
b  ** 2

array([  1,   4, 529], dtype=int32)

In [55]:
b +  e

array([ 2,  4, 26])

In [63]:
[int(i) for i in input().split(" ") if len(i) > 0]

1 2 3 4 


[1, 2, 3, 4]

In [64]:
[[int(i) for i in input().split(" ") if len(i) > 0] for j in range(4)]

1 2 3 4 5 
2 3 4
1 2 
3 24 53 2


[[1, 2, 3, 4, 5], [2, 3, 4], [1, 2], [3, 24, 53, 2]]

In [69]:
size = [int(i) for i in input().split(" ") if len(i) > 0]
if len(size) != 2:
    print("Error")
m, n = size

2 3


In [72]:
[[int(i) for i in input().split(" ") if len(i) > 0] for j in range(m)]

1 2 3
4 5 6


[[1, 2, 3], [4, 5, 6]]

In [81]:
a1d = np.array([1,2,3,4,5,6])
a2d = a1d.reshape((2,3))
a2d.sum(axis=1)

array([ 6, 15])

In [78]:
np.zeros((4, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [99]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
a2d[:, 2:]

(array([3, 6]), array([[1, 2, 3],
        [4, 5, 6]]))

In [107]:
a = np.array([1,2,3])
b = np.array([4,5,6])

((a - b) ** 2).sum()
((a - a.mean()) ** 2).mean(), np.var(a)

(0.66666666666666663, 0.66666666666666663)

In [108]:
import pandas as pd

In [148]:
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
#iris = pd.read_csv("~/iris_data.csv")
type(iris)

pandas.core.frame.DataFrame

In [120]:
iris.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [151]:
iris.columns = ['sl', 'sw', 'pl', 'pw', 'type']

In [125]:
print(iris.head())
print(iris.shape)
print(iris.dtypes)

    sl   sw   pl   pw         type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
(149, 5)
sl      float64
sw      float64
pl      float64
pw      float64
type     object
dtype: object


In [126]:
iris.describe()

sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [132]:
iris[iris.columns[2]]
iris['sw']
iris.sw

0      3.0
1      3.2
2      3.1
3      3.6
4      3.9
5      3.4
6      3.4
7      2.9
8      3.1
9      3.7
10     3.4
11     3.0
12     3.0
13     4.0
14     4.4
15     3.9
16     3.5
17     3.8
18     3.8
19     3.4
20     3.7
21     3.6
22     3.3
23     3.4
24     3.0
25     3.4
26     3.5
27     3.4
28     3.2
29     3.1
      ... 
119    3.2
120    2.8
121    2.8
122    2.7
123    3.3
124    3.2
125    2.8
126    3.0
127    2.8
128    3.0
129    2.8
130    3.8
131    2.8
132    2.8
133    2.6
134    3.0
135    3.4
136    3.1
137    3.0
138    3.1
139    3.1
140    3.1
141    2.7
142    3.2
143    3.3
144    3.0
145    2.5
146    3.0
147    3.4
148    3.0
Name: sw, dtype: float64

In [165]:
#iris['sl'][2:4] = np.nan
type(iris['sl'])
iris.iloc[3:5, 1:3] = np.nan

In [166]:
iris.head()

sl   sw   pl   pw         type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  NaN  NaN  0.2  Iris-setosa
4  5.4  NaN  NaN  0.4  Iris-setosa

In [157]:
iris.describe()

sl          sw          pl          pw
count  149.000000  147.000000  147.000000  149.000000
mean     5.848322    3.041497    3.804762    1.205369
std      0.828594    0.428256    1.752076    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [167]:
#iris.sw = iris.sw.fillna(iris.sw.mean())
iris.sw.fillna(iris.sw.mean(), inplace = True)
iris.head()

sl        sw   pl   pw         type
0  4.9  3.000000  1.4  0.2  Iris-setosa
1  4.7  3.200000  1.3  0.2  Iris-setosa
2  4.6  3.100000  1.5  0.2  Iris-setosa
3  5.0  3.041497  NaN  0.2  Iris-setosa
4  5.4  3.041497  NaN  0.4  Iris-setosa

In [170]:
iris.dropna(inplace = True)
iris.head()

sl   sw   pl   pw         type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa

In [172]:
iris.reset_index(drop = True, inplace = True)
iris.head()

sl   sw   pl   pw         type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  4.6  3.4  1.4  0.3  Iris-setosa
4  5.0  3.4  1.5  0.2  Iris-setosa

In [177]:
iris[iris.type == 'Iris-setosa'].describe()
#iris[iris.pw == 0.2].describe()

sl         sw         pl         pw
count  47.000000  47.000000  47.000000  47.000000
mean    4.995745   3.402128   1.461702   0.242553
std     0.358716   0.385323   0.175144   0.107834
min     4.300000   2.300000   1.000000   0.100000
25%     4.800000   3.100000   1.400000   0.200000
50%     5.000000   3.400000   1.500000   0.200000
75%     5.200000   3.650000   1.550000   0.300000
max     5.800000   4.400000   1.900000   0.600000